INSERT INTO role (id, authority) VALUES (1, 'ADMIN') ON CONFLICT (id) DO NOTHING;
INSERT INTO role (id, authority) VALUES (2, 'MODERATOR') ON CONFLICT (id) DO NOTHING;
INSERT INTO role (id, authority) VALUES (3, 'USER') ON CONFLICT (id) DO NOTHING;
